#!/bin/bash

#Process input data for given date range
hsdata ...hagelslag/config/hrefv2_config/data_preprocess_forecast_multiple_day_hrefv2_2019.config

# Predict using trained ML models on new data
hsforecast .../hagelslag/config/hrefv2_config/forecasting_multiple_day_hrefv2_2019.config -f
hsforecast ...hagelslag/config/hrefv2_config/forecasting_multiple_day_hrefv2_2019.config -g 

#Choose same date range as the above forecasting config files
#Start date is not inclusive
start1=2019-05-31
end1=2019-06-01

curr="$start1"
while true; do
    [ "$curr" \< "$end1" ] || break
    curr=$( date +%Y-%m-%d --date "$curr +1 day" )
    export TRANSFERDATE=$( date +%Y%m%d --date "$curr" )
    export RUNDATE=$( date +%Y-%m-%dT%H:%M --date "$curr" )
    export STARTDATE=$( date +%Y-%m-%dT%H:%M --date "$curr  + 12 hours" )
    export ENDDATE=$( date +%Y-%m-%dT%H:%M --date "$curr + 36 hours" )
    export MEMBERS="arw_00,arw_12,nssl_00,nssl_12,nmmb_00,nmmb_12,nam_00,nam_12"
    echo
    echo $RUNDATE $STARTDATE $ENDDATE $TRANSFERDATE
    echo
   
    #Output netCDF4 or grib2 data using flags. If -y is included, will output hourly data.
    hsfileoutput -r $RUNDATE -s $STARTDATE -e $ENDDATE --ens HREFv2 --map .../hagelslag/mapfiles/hrefv2_2018_map.txt -m Random-Forest -b $MEMBERS -v hail -g 1 -p .../hail_forecasts_grib2_hrefv2_closest_2019/ -o .../hail_graphics_hrefv2_MAXUVV_closest_2019/ --netcdf_out --grib_out -y 

    #Plots are not needed for calibration 
    #Output PNG files of neighborhood maximum ensemble probability of hail (NMEP) or ensemble maximum size of hail
    hsplotter -r $RUNDATE -s $STARTDATE -e $ENDDATE --ens HREFv2 --map .../hagelslag/mapfiles/hrefv2_2018_map.txt -m Random-Forest -b $MEMBERS -v hail -g 1 -p .../hail_forecasts_grib2_hrefv2_closest_2019/ -o .../hail_graphics_hrefv2_MAXUVV_closest_2019/ --nep_out --ens_max_out -y 

    
#Model output calibrated using existing netCDF4 ML NMEP forecasts,

#Creating MESH calibration dataset
python .../hagelslag/hagelslag/util/mrms_mesh_calibration_dataset.py -s 2018-05-01 -e 2018-05-02 -p /Path_to_regridded_MESH_data -o /Path_to_save_calibration_dataset -m .../hagelslag/mapfiles/hrefv2_2018_map.txt -a .../hagelslag/mapfiles/hrefv2_us_mask.nc

#Creating LSR calibration dataset
python .../hagelslag/hagelslag/util/lsr_calibration_dataset.py -s 2018-05-01 -e 2018-08-31 -o /Path_to_save_calibration_dataset -m .../hagelslag/mapfiles/hrefv2_2018_map.txt  

#Train on the same date range as the output netCDF4 forecasts above
hscalibration .../hagelslag/config/hrefv2_config/calibration_multiple_day_hrefv2_2019.config -t

#Forecast for multiple date range. If -y is included, will output hourly data.
hscalibration .../hagelslag/config/hrefv2_config/calibration_multiple_day_hrefv2_2019.config -f -n -g -y 
